controller_list = [
    # {"router": loginController, "tags": ["登录模块"]},
    # {"router": captchaController, "tags": ["验证码模块"]},
    # {"router": userController, "tags": ["系统管理-用户管理"]},
    # {"router": roleController, "tags": ["系统管理-角色管理"]},
    # {"router": menuController, "tags": ["系统管理-菜单管理"]},
    # {"router": deptController, "tags": ["系统管理-部门管理"]},
    # {"router": postController, "tags": ["系统管理-岗位管理"]},
    # {"router": dictController, "tags": ["系统管理-字典管理"]},
    # {"router": configController, "tags": ["系统管理-参数管理"]},
    # {"router": noticeController, "tags": ["系统管理-通知公告管理"]},
    # {"router": logController, "tags": ["系统管理-日志管理"]},
    # {"router": onlineController, "tags": ["系统监控-在线用户"]},
    # {"router": jobController, "tags": ["系统监控-定时任务"]},
    # {"router": serverController, "tags": ["系统监控-菜单管理"]},
    # {"router": cacheController, "tags": ["系统监控-缓存监控"]},
    # {"router": commonController, "tags": ["通用模块"]},
    # {"router": genController, "tags": ["代码生成"]},
]
